### ISSUE TITLE
Instructions to run the install script

### ISSUE THREAD

**Issue by qwo** [lynnaloo/xtuple-vagrant#1]
After connecting to the virtual machine it prompts the user to install node-data source.

as per the original xtuple/xtuple instructions, it suggests to install the client
1. Run the install script

bash scripts/install_xtuple.sh
You will be prompted for sudo credentials; installation will take a few minutes.

**Comment by qwo** [comment]
closed i can't read

**Comment by lynnaloo** [comment]
You just need to take off the Google Glass and put on your real glasses :)
