### ISSUE TITLE
yml-based build

### ISSUE THREAD

**Issue by tjwebb** [lynnaloo/xtuple-vagrant#11]
Hey @lynnaloo didn't you say there was a `.yml`-based version of this that you had started somewhere? Can you point me to it?

**Comment by lynnaloo** [comment]
https://github.com/lynnaloo/xtuple-vagrant/tree/test-server

I just pasted the commands from the `.yml` in the provisioning file for now to see if it would work (it didn't: https://github.com/xtuple/xtuple-server/issues/287) and step #2 after it installed correctly was to use yml directly in the Vagrantfile.

**Comment by lynnaloo** [comment]
If you can separate out just the commands that Vagrant needs into a separate `.yml` file then that will help as well. I can just `include yaml` in the `Vagrantfile` and provision with each line in the file.

**Comment by tjwebb** [comment]
Cool thanks
