### ISSUE TITLE
vagrant locale setting in Vagrantfile

### ISSUE THREAD

**Issue by tjwebb** [lynnaloo/xtuple-vagrant#12]
https://github.com/lynnaloo/xtuple-vagrant/blob/master/Vagrantfile#L84

> config.vm.provision "shell", inline: 'update-locale LC_ALL="en_US.utf8"'

The xtuple-server now sets these automatically:
https://github.com/xtuple/xtuple-server/blob/master/tasks/pg/config/postgresql-9.3.conf.template#L523-L527

I need to look into see whether I should use the `LC_ALL` variable, as Vagrant does, or continue using my current method of determining locale

**Comment by lynnaloo** [comment]
That line is something that John found on StackOverflow to fix the Postgres issue he was seeing. I'm not tied to that solution if yours does the job.

**Comment by tjwebb** [comment]
Ok yea; this is mostly a TODO to remind me to check whether xtuple-server conflicts with this.
