### ISSUE TITLE
[FAQ]: VirtualBox is complaining that the kernel module is not loaded

### ISSUE THREAD

**Issue by tjwebb** [lynnaloo/xtuple-vagrant#13]
For some reason my Ubuntu 14.04 started giving me this suddenly:

```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
```

I fixed it by doing this:

``` bash
tjwebb@latitude:xtuple-vagrant (master) $ sudo /etc/init.d/vboxdrv setup
[sudo] password for tjwebb: 
Stopping VirtualBox kernel modules ...done.
Recompiling VirtualBox kernel modules ...done.
Starting VirtualBox kernel modules ...done.
```

**Comment by lynnaloo** [comment]
Did you upgrade to 14 from the precise64 Ubuntu 12.04 base box? You should use a different base box if you want 14.

**Comment by tjwebb** [comment]
No this failed before it even loaded the Vagrantfile or anything. It was a pure Virtualbox fail.

EDIT: Oh sorry, by "my Ubuntu 14.04", I mean my host is `14.04`, not the guest. My bad. The guest is just the usual precise64 image

**Comment by tjwebb** [comment]
This is documentation of an issue I ran into using Ubuntu 14.04 as a host, along with the fix for it. Maybe someone else with 14.04 might run into this issue too.

**Comment by lynnaloo** [comment]
I ran into this on Windows and there are people online who have seen it on OSX as well. Sometimes after you update your OS, VirtualBox then doesn't know how to talk to your existing VM (Vboxmanage). Re-installing solved the issue in the other cases for me, but VB also supposedly fixed the issue in a later version.

**Comment by rhchristian** [comment]
Thank you, tjwebb this worked for me.  (Ubuntu 14.04)

**Comment by tjwebb** [comment]
you're welcome @rhchristian

**Comment by aeinsights** [comment]
@tjwebb This helps me too... Thanks

**Comment by rehrumesh** [comment]
Saved my time. Thanks @tjwebb

**Comment by NikLP** [comment]
Instant fix for me too on an Ionic VM install. Thanks!

**Comment by nasry** [comment]
thanks you save my life @tjwebb

**Comment by aznain** [comment]
Thanks @tjwebb . Worked for me too on 14.04 using VirtualBox 5.0.2r102096.

**Comment by SanderSander** [comment]
Thanks @tjwebb Same here for 14.04 and VirtualBox 5.0.4

**Comment by chaim1221** [comment]
Thanks @tjwebb

**Comment by mateusfreira** [comment]
Thanks @tjwebb

**Comment by rollbackpt** [comment]
Thanks a lot @tjwebb ;)

**Comment by mehrancodes** [comment]
After Updating my Ubuntu, it happened to my virtual box too.
Thanks @tjwebb

**Comment by alcarruth** [comment]
Back in business.
Thanks @tjwebb !

**Comment by SamuelMartens** [comment]
@tjwebb Thank you man!

**Comment by brunocascio** [comment]
Thanks @tjwebb

**Comment by dwayne** [comment]
Thanks @tjwebb.

**Comment by Lyla-Fischer** [comment]
Thanks @tjwebb

**Comment by ozgurhalilince** [comment]
Thanks a lot @tjwebb

**Comment by dasebast** [comment]
@tjwebb Thanks for the solution mate.

**Comment by roshimon** [comment]
I hit the same issue today after upgrading to 5.0.14 (I am on Ubuntu 15.10, using the official Virtualbox apt repo)

I fixed it with:

sudo /usr/lib/virtualbox/vboxdrv.sh setup

**Comment by pauvos** [comment]
@tjwebb Thanks mate!

**Comment by sachin1753** [comment]
Thanks @tjwebb, it worked for me

**Comment by ryeballar** [comment]
Thanks @roshimon, that really helped me!

**Comment by danielsunyu** [comment]
Thanks @tjwebb You saved my trouble!

**Comment by roshimon** [comment]
@ryeballar glad to know it really helped you :)

**Comment by tgabi333** [comment]
Thanks @tjwebb

**Comment by Serpalnik** [comment]
@tjwebb thx a lot!

**Comment by vzabaznov** [comment]
@tjwebb  thx a lot!!

**Comment by zappen999** [comment]
@tjwebb Thanks!

**Comment by Haroldgomez777** [comment]
@tjwebb thanks

**Comment by thiruworkspace** [comment]
Thanks

**Comment by kevinhowbrook** [comment]
In my case : 
`sudo: /etc/init.d/vboxdrv: command not found`

So I ran
`sudo: /etc/init.d/vboxdrv: command not found`

The real reason here is to recompile the kernel

This solved it for me. Thanks @tjwebb too

**Comment by CdavM** [comment]
@kevinhowbrook  What did you end up running?

**Comment by taitai42** [comment]
@CdavM   `sudo /sbin/rcvboxdrv setup`

**Comment by neonecosystem** [comment]
Uninstalling modules from DKMS
  removing old DKMS module vboxhost version  5.0.2

---

Deleting module version: 5.0.2

## completely from the DKMS tree.

Done.
Attempting to install using DKMS

Creating symlink /var/lib/dkms/vboxhost/5.0.2/source ->
                 /usr/src/vboxhost-5.0.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-46-generic -C /lib/modules/4.4.0-46-generic/build M=/var/lib/dkms/vboxhost/5.0.2/build....(bad exit status: 2)
Failed to install using DKMS, attempting to install without
make KBUILD_VERBOSE=1 SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 CONFIG_MODULE_SIG= -C /lib/modules/4.4.0-46-generic/build modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
mkdir -p /tmp/vbox.0/.tmp_versions ; rm -f /tmp/vbox.0/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/tmp/vbox.0
  gcc -Wp,-MD,/tmp/vbox.0/linux/.SUPDrv-linux.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include  -I./arch/x86/include -Iarch/x86/$
/tmp/vbox.0/linux/SUPDrv-linux.c: In function  ^ ^ VBoxDrvLinuxUnload ^ ^ :
/tmp/vbox.0/linux/SUPDrv-linux.c:487:8: error: void value not ignored as it ought to be
     rc = misc_deregister(&gMiscDeviceUsr);
        ^
                                                               [ Read 45 lines ]
^G Get Help     ^O Write Out    ^W Where Is     ^K Cut Text     ^J Justify      ^C Cur Pos      ^Y Prev Page    M-\ First Line  M-W WhereIs Next
^X Exit         ^R Read File    ^\ Replace      ^U Uncut Text   ^T To Spell     ^_ Go To Line   ^V Next Page    M-/ Last Line   M-] To Bracket
        ^
scripts/Makefile.build:258: recipe for target '/tmp/vbox.0/linux/SUPDrv-linux.o' failed
make[2]: **\* [/tmp/vbox.0/linux/SUPDrv-linux.o] Error 1
Makefile:1418: recipe for target '_module_/tmp/vbox.0' failed
make[1]: **\* [_module_/tmp/vbox.0] Error 2
Makefile:298: recipe for target 'vboxdrv' failed
make: **\* [vboxdrv] Error 2

**Comment by neonecosystem** [comment]
this is my log. pls help

**Comment by kevinhowbrook** [comment]
@neonecosystem I had a similar issue in the past related to Secure booting not allowing third parties.
running `sudo apt-get --reinstall install virtualbox-dkms` enabled me to turn it off, that might help

**Comment by andkirby** [comment]
Guys, what about Debian 8?

I have similar directory:
```
/usr/share/virtualbox/src/vboxhost/vboxdrv
$ ll
total 712
-rw-r--r--  1 root root  10443 Nov 21 18:23 Makefile
-rw-r--r--  1 root root 224222 Aug 22 06:59 SUPDrv.c
-rw-r--r--  1 root root  41624 Aug 22 06:59 SUPDrvDTrace.c
-rw-r--r--  1 root root 185328 Oct 17 12:07 SUPDrvGip.c
-rw-r--r--  3 root root   8835 Aug 22 06:59 SUPDrvIDC.h
-rw-r--r--  1 root root  55693 Oct 17 12:07 SUPDrvIOC.h
-rw-r--r--  1 root root  41053 Oct 17 12:07 SUPDrvInternal.h
-rw-r--r--  1 root root  13162 Aug 22 06:59 SUPDrvSem.c
-rw-r--r--  1 root root  91951 Aug 22 06:59 SUPDrvTracer.c
-rw-r--r--  1 root root  10997 Aug 22 06:59 SUPLibAll.c
drwxr-xr-x  2 root root     23 Nov 28 00:44 VBox
drwxr-xr-x 10 root root    100 Nov 28 00:44 common
drwxr-xr-x  2 root root   4096 Nov 28 00:44 generic
drwxr-xr-x  5 root root     43 Nov 28 00:44 include
drwxr-xr-x  2 root root     27 Nov 28 00:44 linux
drwxr-xr-x  3 root root     16 Nov 28 00:44 math
-rw-r--r--  4 root root    256 Nov 21 18:22 product-generated.h
drwxr-xr-x  4 root root   4096 Nov 28 00:44 r0drv
-rw-r--r--  4 root root     28 Nov 21 18:23 revision-generated.h
-rw-r--r--  4 root root    338 Nov 21 18:22 version-generated.h
```

**Comment by dahousecat** [comment]
Thanks, great fix. I have to do this after every time I restart my computer.

**Comment by Angelo8828** [comment]
@tjwebb Nice, thanks!

**Comment by jakazzy** [comment]
After running this: sudo /usr/lib/virtualbox/vboxdrv.sh setup,  I'm getting this error:
vboxdrv.sh: Stopping VirtualBox services.
vboxdrv.sh: Building VirtualBox kernel modules.
vboxdrv.sh: Starting VirtualBox services.
vboxdrv.sh: Building VirtualBox kernel modules.
vboxdrv.sh: failed: modprobe vboxdrv failed.
