### ISSUE TITLE
Documentation ???

### ISSUE THREAD

**Issue by ghost** [lynnaloo/xtuple-vagrant#14]
Can anybody point me to ANY developer documentation that might exist.  An overview of the classes?  Class hierarchy?  Development standards? Anything?

Thanks

**Comment by lynnaloo** [comment]
Most of the xTuple development documentation should be [here](https://github.com/xtuple/xtuple/wiki). If there's something specific you're looking for that's not there, put an issue in [here](https://github.com/xtuple/xtuple/issues) and we'll find it for you or create it!

**Comment by ghost** [comment]
Thanks Linda.  Much Appreciated!   :-)
